name: Build and Push Docker Image Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/build-n-push-backend.yml'
  # También puedes agregar tags para versionar imágenes
  # tags:
  #   - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_USER: admin
    #       POSTGRES_PASSWORD: postgresql
    #       POSTGRES_DB: my_database
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd="pg_isready -U admin"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            eldioni/docker-backend:1.2
            eldioni/docker-backend:${{ github.sha }}

      # - name: Pull official PostgreSQL image
      #   run: docker pull postgres:15

      # - name: Retag image with your Docker Hub namespace
      #   run: docker tag postgres:15 eldioni/postgres:15

      # - name: Push image to Docker Hub
      #   run: docker push eldioni/postgres:15

