name: Build and Push Docker Image Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-n-push-frontend.yml'
  # También puedes agregar tags para versionar imágenes
  # tags:
  #   - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            eldioni/docker-frontend:1.2
            eldioni/docker-frontend:${{ github.sha }}

      # - name: Pull official PostgreSQL image
      #   run: docker pull postgres:15

      # - name: Retag image with your Docker Hub namespace
      #   run: docker tag postgres:15 eldioni/postgres:15

      # - name: Push image to Docker Hub
      #   run: docker push eldioni/postgres:15

