name: Deploy PostgreSql to Cloud SQL

on:
  workflow_run:
    workflows: ["Deploy Docker Images to Cloud Run"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup to Cloud Run
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

       # Crear instancia de Cloud SQL si no existe
      - name: Create Cloud SQL Instance
        run: |
          gcloud sql instances create postgresql-cloudsql \
            --database-version=POSTGRES_15 \
            --tier=db-f1-micro \
            --region=us-central1 \
            --root-password="${{ secrets.DB_ROOT_PASSWORD }}" || echo "Instance already exists"

      # Crear base de datos
      - name: Create database
        run: |
          gcloud sql databases create my_database \
            --instance=postgresql-cloudsql || echo "Database already exists"

      # Crear usuario
      - name: Create user
        run: |
          gcloud sql users create admin \
            --instance=postgresql-cloudsql \
            --password="${{ secrets.DB_PASSWORD }}" || echo "User exists"

      # Subir script y ejecutarlo en Cloud SQL
        # Habilita el cliente de PostgreSQL
        # Abre túnel temporal hacia la instancia con gcloud
      - name: Run init SQL
        env:
          DB_USER: admin
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_NAME: my_database
          INSTANCE: postgresql-cloudsql
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client

          gcloud sql connect $INSTANCE --user=$DB_USER --quiet -- \
            bash -c "PGPASSWORD=$DB_PASS psql -U $DB_USER -d $DB_NAME -f database/init.sql"

