name: Deploy Docker Images to Cloud Run

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup to Cloud Run
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy backend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: backend-service
          region: us-central1
          image: docker.io/eldioni/docker-backend:${{ github.run_number }}

      - name: Deploy frontend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: frontend-service
          region: us-central1
          image: docker.io/eldioni/docker-frontend:${{ github.run_number }}