name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  # También puedes agregar tags para versionar imágenes
  # tags:
  #   - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            eldioni/docker-backend:1.2
            eldioni/docker-backend:${{ github.run_number }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            eldioni/docker-frontend:1.2
            eldioni/docker-frontend:${{ github.run_number }}

      - name: Pull official PostgreSQL image
        run: docker pull postgres:15

      - name: Retag image with your Docker Hub namespace
        run: docker tag postgres:15 eldioni/postgres:15

      - name: Push image to Docker Hub
        run: docker push eldioni/postgres:15

      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run database
        run: |
          gcloud run deploy postgres \
            --image=docker.io/eldioni/postgres:15 \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
      
      - name: Deploy to Cloud Run backend
        run: |
          gcloud run deploy docker-backend \
            --image=docker.io/eldioni/docker-backend:${{ github.run_number }} \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated

      - name: Deploy to Cloud Run frontend
        run: |
          gcloud run deploy docker-frontend \
            --image=docker.io/eldioni/docker-frontend:${{ github.run_number }} \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated